server:
  port: 8083
  servlet:
    context-path: /wxp

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spbt
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null

dubbo:
  application:
    name: wxp-api
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    register: true
    group: dubbo
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: registry



