server:
  port: 8002



dubbo:
  application:
    name: wxp-provider
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
mybatis:
  mapper-locations: /mapping/*.xml
spring:
  datasource:
    name: hive
    password: hive
    url: jdbc:hive2://localhost:10000/default
    driver-class-name: org.apache.hive.jdbc.HiveDriver





